const redirects = [
  {
    source: "/print",
    destination: "/drukwerk",
    permanent: true,
  },
  { source: "/print/boeken", destination: "/drukwerk/commercieel-drukwerk", permanent: true },
  { source: "/print/brochures", destination: "/drukwerk/corporate-drukwerk", permanent: true },
  { source: "/print/admin", destination: "/drukwerk", permanent: true },
  { source: "/print/kalenders", destination: "/drukwerk/kalenders", permanent: true },
  { source: "/print/de-druivelaar", destination: "/realisaties/de-groene-druivelaar", permanent: true },
  { source: "/ticket", destination: "/drukwerk/tickets", permanent: true },
  { source: "/security", destination: "/drukwerk/security", permanent: true },
  { source: "/data", destination: "/diensten/digitaal-platform-okapi", permanent: true },
  { source: "/webtoprint", destination: "/web2print", permanent: true },
  { source: "/crossmedia-marketing", destination: "/diensten", permanent: true },
  { source: "/categorie/:category", destination: "/blog", permanent: true },
  { source: "/data/:slug", destination: "/blog", permanent: true },
  { source: "/publishers-2", destination: "/over-ons", permanent: true },
  { source: "/vacatures", destination: "/werkenbijinnigroup", permanent: true },
  { source: "/vacature/:slug", destination: "/werkenbijinnigroup/:slug", permanent: true },
  { source: "/login", destination: "/web2print", permanent: true },

  // EN
  { source: "/en/home-3", destination: "/en", permanent: true },
  { source: "/en/print-2", destination: "/en/drukwerk", permanent: true },
  { source: "/en/print-2/books", destination: "/en/drukwerk/commercieel-drukwerk", permanent: true },
  { source: "/en/print-2/brochures", destination: "/en/drukwerk/corporate-drukwerk", permanent: true },
  { source: "/en/print-2/admin", destination: "/en/drukwerk", permanent: true },
  { source: "/en/print-2/calendars", destination: "/en/drukwerk/kalenders", permanent: true },
  { source: "/en/print-2/druivelaar", destination: "/en/realisaties/de-groene-druivelaar", permanent: true },
  { source: "/en/ticket-3", destination: "/en/drukwerk/tickets", permanent: true },
  { source: "/en/security-3", destination: "/en/drukwerk/security", permanent: true },
  { source: "/en/data-3", destination: "/en/diensten/digitaal-platform-okapi", permanent: true },
  { source: "/en/web-to-print-2", destination: "/en/web2print", permanent: true },
  { source: "/en/crossmedia-marketing", destination: "/en/diensten", permanent: true },
  { source: "/en/categorie/:category", destination: "/en/blog", permanent: true },
  { source: "/en/data-en/:slug", destination: "/en/blog", permanent: true },
  { source: "/en/publishers", destination: "/en/over-ons", permanent: true },
  { source: "/en/login-en", destination: "/en/web2print", permanent: true },
  { source: "/en/contact-3", destination: "/en/contact", permanent: true },

  // FR
  { source: "/fr/home-2", destination: "/fr", permanent: true },
  { source: "/fr/impression", destination: "/fr/drukwerk", permanent: true },
  { source: "/fr/impression/livres", destination: "/fr/drukwerk/commercieel-drukwerk", permanent: true },
  { source: "/fr/impression/brochures", destination: "/fr/drukwerk/corporate-drukwerk", permanent: true },
  { source: "/fr/impression/admin", destination: "/fr/drukwerk", permanent: true },
  { source: "/fr/impression/calendriers", destination: "/fr/drukwerk/kalenders", permanent: true },
  {
    source: "/fr/impression/le-sablier",
    destination: "/fr/realisaties/de-groene-druivelaar",
    permanent: true,
  },
  { source: "/fr/ticket-2", destination: "/fr/drukwerk/tickets", permanent: true },
  { source: "/fr/securite", destination: "/fr/drukwerk/security", permanent: true },
  { source: "/fr/data-2", destination: "/fr/diensten/digitaal-platform-okapi", permanent: true },
  { source: "/fr/web-to-print", destination: "/fr/web2print", permanent: true },
  { source: "/fr/communication-cross-media", destination: "/fr/diensten", permanent: true },
  { source: "/fr/publication", destination: "/fr/over-ons", permanent: true },
  { source: "/fr/login-fr", destination: "/fr/web2print", permanent: true },
  { source: "/fr/contact-2", destination: "/fr/contact", permanent: true },
];

module.exports = redirects;
